name = "GenieBuilder"
uuid = "c9453c14-af8a-11ec-351d-c7c9a2035d70"
authors = ["Adrian Salceanu"]
version = "0.12.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieAutoReload = "c6228e60-a24f-11e9-1776-c313472ebacc"
GenieDevTools = "4e5d9629-6565-4102-a9ff-45c707eb060e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
RemoteREPL = "1bd9f7bb-701c-4338-bec7-ac987af7c555"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"

[compat]
Genie = "5.3"
GenieAutoReload = "2"
GenieDevTools = "1"
HTTP = "1"
Inflector = "1"
JSON3 = "1.9"
RemoteREPL = "0.2"
SearchLight = "2"
SearchLightSQLite = "2"
Stipple = "0.24, 0.25"
julia = "1.6"
