name = "GenieBuilder"
uuid = "c9453c14-af8a-11ec-351d-c7c9a2035d70"
authors = ["Adrian Salceanu"]
version = "0.15.11"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieAutoReload = "c6228e60-a24f-11e9-1776-c313472ebacc"
GenieDevTools = "4e5d9629-6565-4102-a9ff-45c707eb060e"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
RemoteREPL = "1bd9f7bb-701c-4338-bec7-ac987af7c555"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
Genie = "5.18"
GenieAutoReload = "2"
GenieDevTools = "2.1.2"
Git = "1.3"
HTTP = "1"
Inflector = "1"
JSON3 = "1.9"
RemoteREPL = "0.2"
Scratch = "1.1"
SearchLight = "2.10"
SearchLightSQLite = "2.2.1"
Stipple = "0.27"
StippleUI = "0.22"
ZipFile = "0.10"
julia = "1.6"
